/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheSpaceRouteImport } from './routes/the-space'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Level5RouteImport } from './routes/level-5'
import { Route as Level4RouteImport } from './routes/level-4'
import { Route as HomepageRouteImport } from './routes/homepage'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperationsReservationsRouteImport } from './routes/operations.reservations'
import { Route as OperationsOrdersRouteImport } from './routes/operations.orders'
import { Route as OperationsMessagesRouteImport } from './routes/operations.messages'

const TheSpaceRoute = TheSpaceRouteImport.update({
  id: '/the-space',
  path: '/the-space',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Level5Route = Level5RouteImport.update({
  id: '/level-5',
  path: '/level-5',
  getParentRoute: () => rootRouteImport,
} as any)
const Level4Route = Level4RouteImport.update({
  id: '/level-4',
  path: '/level-4',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRoute = HomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsReservationsRoute = OperationsReservationsRouteImport.update({
  id: '/operations/reservations',
  path: '/operations/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsOrdersRoute = OperationsOrdersRouteImport.update({
  id: '/operations/orders',
  path: '/operations/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsMessagesRoute = OperationsMessagesRouteImport.update({
  id: '/operations/messages',
  path: '/operations/messages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/homepage': typeof HomepageRoute
  '/level-4': typeof Level4Route
  '/level-5': typeof Level5Route
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/the-space': typeof TheSpaceRoute
  '/operations/messages': typeof OperationsMessagesRoute
  '/operations/orders': typeof OperationsOrdersRoute
  '/operations/reservations': typeof OperationsReservationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/homepage': typeof HomepageRoute
  '/level-4': typeof Level4Route
  '/level-5': typeof Level5Route
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/the-space': typeof TheSpaceRoute
  '/operations/messages': typeof OperationsMessagesRoute
  '/operations/orders': typeof OperationsOrdersRoute
  '/operations/reservations': typeof OperationsReservationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/homepage': typeof HomepageRoute
  '/level-4': typeof Level4Route
  '/level-5': typeof Level5Route
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/the-space': typeof TheSpaceRoute
  '/operations/messages': typeof OperationsMessagesRoute
  '/operations/orders': typeof OperationsOrdersRoute
  '/operations/reservations': typeof OperationsReservationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/contact'
    | '/forgot-password'
    | '/gallery'
    | '/homepage'
    | '/level-4'
    | '/level-5'
    | '/login'
    | '/menu'
    | '/reservations'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/the-space'
    | '/operations/messages'
    | '/operations/orders'
    | '/operations/reservations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/contact'
    | '/forgot-password'
    | '/gallery'
    | '/homepage'
    | '/level-4'
    | '/level-5'
    | '/login'
    | '/menu'
    | '/reservations'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/the-space'
    | '/operations/messages'
    | '/operations/orders'
    | '/operations/reservations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/contact'
    | '/forgot-password'
    | '/gallery'
    | '/homepage'
    | '/level-4'
    | '/level-5'
    | '/login'
    | '/menu'
    | '/reservations'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/the-space'
    | '/operations/messages'
    | '/operations/orders'
    | '/operations/reservations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  HomepageRoute: typeof HomepageRoute
  Level4Route: typeof Level4Route
  Level5Route: typeof Level5Route
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  ReservationsRoute: typeof ReservationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TheSpaceRoute: typeof TheSpaceRoute
  OperationsMessagesRoute: typeof OperationsMessagesRoute
  OperationsOrdersRoute: typeof OperationsOrdersRoute
  OperationsReservationsRoute: typeof OperationsReservationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-space': {
      id: '/the-space'
      path: '/the-space'
      fullPath: '/the-space'
      preLoaderRoute: typeof TheSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-5': {
      id: '/level-5'
      path: '/level-5'
      fullPath: '/level-5'
      preLoaderRoute: typeof Level5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-4': {
      id: '/level-4'
      path: '/level-4'
      fullPath: '/level-4'
      preLoaderRoute: typeof Level4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage': {
      id: '/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/reservations': {
      id: '/operations/reservations'
      path: '/operations/reservations'
      fullPath: '/operations/reservations'
      preLoaderRoute: typeof OperationsReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/orders': {
      id: '/operations/orders'
      path: '/operations/orders'
      fullPath: '/operations/orders'
      preLoaderRoute: typeof OperationsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/messages': {
      id: '/operations/messages'
      path: '/operations/messages'
      fullPath: '/operations/messages'
      preLoaderRoute: typeof OperationsMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  HomepageRoute: HomepageRoute,
  Level4Route: Level4Route,
  Level5Route: Level5Route,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  ReservationsRoute: ReservationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TheSpaceRoute: TheSpaceRoute,
  OperationsMessagesRoute: OperationsMessagesRoute,
  OperationsOrdersRoute: OperationsOrdersRoute,
  OperationsReservationsRoute: OperationsReservationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
